services:
    postgres:
        image: postgres:latest
        container_name: postgres_big_data_lab2
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: database
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./sql_scripts:/docker-entrypoint-initdb.d
            - ./исходные данные:/mock_data

    spark:
        image: jupyter/pyspark-notebook:latest
        container_name: spark_big_data_lab2
        environment:
            JUPYTER_TOKEN: "password"
        ports:
            - "4040:4040" # Spark UI
            - "8888:8888" # Jupyter Notebook
        volumes:
            - ./notebooks:/home/jovyan/work
            - ./jars:/opt/spark/jars

volumes:
    postgres_data: